export { trendingData } from './api/print.js'
export { fixTitle } from './utils/dom.js'
export { getTrendingMovies } from './api/trendingGetters.js'
export { printMedia } from './api/printMedia.js'
export { createTrendingList } from './dom-manipulator/createList.js'